---
title: "Smarter Jittering for Scatterplot"
format: html
---

<!-- Name suggestions-->
<!--1. Jitter, But Better with Scatterplots-->
<!--2. Smarter Jittering for Scatterplots -->

**Abstract** 
<!-- For various reasons it is useful for spreading points in dotplot or scatterplot displays. When points are overplotted in a display the assessment of the distribution or association between variables may not be accurately interpreted. There is a long history of using dotplots for examining distributions, with a variety of recommended methods for spreading apart identical points.  -->


<!-- In this work, methods for adding controlled random noise in two dimensions (i.e. jittering) are introduced. The main goal for this consist in making it easier to visualize overlapping data points in scatter plots where both x and y variables may have discrete or semi-discrete values.   -->


<!-- Two main parameters are combined to create a two-dimensional jittering of points. First the noise generation, which can be random based on a standard distribution like \textit{uniform} or \textit{Gaussian}, or using a quasi-random scheme such as \textit{Sobolev} sequence. Second, it is possible to add directionality or correlation to the noise. This correlation is set based on a global pattern of the points or local where only is affected by closer data points. -->


<!-- The methods are implemented in `gscatie` R package that extends `geom_jitter()` on two dimensions, and is accecible on https://github.com/natydasilva/ggscatie  -->

Overlapping points in scatterplots can hide important patterns, making it hard to see how data are distributed or related especially when values are discrete or take only a few levels. Jittering is often used to spread points apart, but most existing methods simply add small, independent noise to each axis.

We introduce a new approach to jittering in two dimensions that spreads overlapping points more effectively while still reflecting the structure of the data. The method allows different ways of generating noise such as uniform, Gaussian, or quasi-random (Sobolev) patterns and can also control the direction and alignment of the spread. This can be applied either across the whole dataset or locally, based on nearby points.

These methods are implemented in the `ggscatite` R package, which extends `geom_jitter()` to support coordinated two-dimensional jittering. This gives users more control over how points are displayed and makes dense scatterplots easier to interpret.



**Authors**: 
Natalia da Silva, Ignacio Alvarez-Castro, Dianne Cook & Jayani P., Gamage.

**github**: 
https://github.com/natydasilva/ggscatite 

